const callself = require('callself')
try {
  callself.makeTheCall()
} catch (e) {
  throw new Error('Referencing exported functions should be possible', { cause: e });
}